server:
  port: 8080
spring:
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: test
mybatis-plus:
  #Info output config
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl